# Generated by Django 4.2.4 on 2023-10-03 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumaccess',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_accesses', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='albumaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_accessing_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
