# Generated by Django 4.2.2 on 2023-07-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/default.jpg', null=True, upload_to='profile_pictures/', verbose_name='profile picture'),
        ),
    ]
