# Generated by Django 4.2.4 on 2023-09-09 12:59

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='profile_pictures/', verbose_name='profile picture'),
        ),
    ]
