# Generated by Django 4.2.4 on 2023-09-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo_limit',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
