# Generated by Django 4.2.2 on 2023-07-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_bio_customuser_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRelation',
        ),
    ]
