# Generated by Django 4.2.2 on 2023-08-06 13:06

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_relationrequest_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='profile_pictures/', verbose_name='profile picture'),
        ),
    ]
