# Generated by Django 4.2.4 on 2023-08-20 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0007_alter_customuser_bio_alter_customuser_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerned_user_notif', to=settings.AUTH_USER_MODEL)),
                ('user_sending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user_notif', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
