# Generated by Django 4.2.4 on 2023-08-20 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_sending',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_user_notif', to=settings.AUTH_USER_MODEL),
        ),
    ]
