# Generated by Django 4.2.4 on 2023-08-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_notification_user_sending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user_sending',
        ),
        migrations.AddField(
            model_name='notification',
            name='identifier',
            field=models.CharField(default='default-identifier', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
