# Generated by Django 4.2.4 on 2023-09-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='premium_member',
            field=models.BooleanField(default=False),
        ),
    ]
