from django import forms
import json
from django.utils.translation import gettext_lazy as _

class FeedbackForm(forms.Form):
    feedback = forms.CharField(
        widget=forms.Textarea(attrs={'class':'w-full textarea textarea-bordered text-sm',
                                     'placeholder':_('Give a feedback and/or ideas..'),
                                     'rows':'4'}),
        required=True,
        label=""
    )

class DemoForm(forms.Form):
    user_email = forms.ChoiceField(widget=forms.Select(attrs={'class': 'select select-bordered w-full max-w-xs text-base'}))

    def __init__(self, *args, **kwargs):
        super(DemoForm, self).__init__(*args, **kwargs)
        self.fields['user_email'].choices = self.get_choices()

    def get_choices(self):
        # Path to the JSON file generated by the bash script
        filepath = 'staticfiles/shell_scripts/emails.json'
        try:
            with open(filepath, 'r') as f:
                data = json.load(f)
                choices = [(d['email'], f"{d['name']}") for d in data]
                return choices
        except FileNotFoundError:
            return []
