# Generated by Django 4.2.2 on 2023-07-23 21:05

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to=photos.models.album_photo_directory_path),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
