# Generated by Django 4.2.2 on 2023-07-24 15:02

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=photos.models.album_photo_directory_path),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('album',), name='unique_default_photo_per_album'),
        ),
    ]
