# Generated by Django 4.2.2 on 2023-08-06 13:32

from django.db import migrations
import photos.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to=photos.models.album_photo_directory_path),
        ),
    ]
