# Generated by Django 4.2.4 on 2023-08-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_likes', '0003_alter_comment_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
