# Generated by Django 4.2.4 on 2023-08-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_likes', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
    ]
