# Generated by Django 4.2.2 on 2023-07-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='user_sender',
            new_name='user_sending',
        ),
    ]
