# Generated by Django 4.2.2 on 2023-07-29 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access', '0003_alter_relation_relation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationrequest',
            name='relation_type',
            field=models.CharField(choices=[('SIBLING', 'SIBLING'), ('PARENT/CHILDREN', 'PARENT/CHILDREN'), ('COUSIN', 'COUSIN'), ('AUNT-UNCLE/NEPHEW-NIECE', 'AUNT-UNCLE/NEPHEW-NIECE'), ('GRANDPARENT/GRANDCHILDREN', 'GRANDPARENT/GRANDCHILDREN'), ('BROTHER/SISTER IN LAW', 'BROTHER/SISTER IN LAW'), ('FRIEND', 'FRIEND'), ('UNDEFINED', 'UNDEFINED')], default='UNDEFINED', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='relationrequest',
            unique_together={('user_receiving', 'user_sending')},
        ),
    ]
