# Generated by Django 4.2.2 on 2023-07-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_alter_relationrequest_relation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='relation_type',
            field=models.CharField(choices=[('UNDEFINED', 'UNDEFINED'), ('SIBLING', 'SIBLING'), ('PARENT/CHILDREN', 'PARENT/CHILDREN'), ('COUSIN', 'COUSIN'), ('AUNT-UNCLE/NEPHEW-NIECE', 'AUNT-UNCLE/NEPHEW-NIECE'), ('GRANDPARENT/GRANDCHILDREN', 'GRANDPARENT/GRANDCHILDREN'), ('BROTHER/SISTER IN LAW', 'BROTHER/SISTER IN LAW'), ('FRIEND', 'FRIEND')], default='UNDEFINED', max_length=50),
        ),
    ]
