# Generated by Django 4.2.2 on 2023-07-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_alter_relation_relation_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='relationrequest',
            name='user_receiving',
        ),
        migrations.RemoveField(
            model_name='relationrequest',
            name='user_sending',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
        migrations.DeleteModel(
            name='RelationRequest',
        ),
    ]
