# Generated by Django 4.2.2 on 2023-07-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_alter_relationrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumAccessRequest',
        ),
    ]
