# Generated by Django 4.2.2 on 2023-08-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_delete_albumaccessrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumaccess',
            name='has_access',
        ),
    ]
