# Generated by Django 4.2.2 on 2023-08-01 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0001_initial'),
        ('access', '0010_alter_albumaccess_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='albumaccess',
            unique_together={('album', 'user')},
        ),
    ]
